local M = {}

M.cmp_kind = {
  Class = { icon = "ﴯ", name = "Class" },
  Color = { icon = "", name = "Color" },
  Constant = { icon = "", name = "Const" },
  Constructor = { icon = "", name = "Ctor" },
  Enum = { icon = "", name = "Enum" },
  EnumMember = { icon = "", name = "EnumMember" },
  Event = { icon = "", name = "Event" },
  Field = { icon = "ﰠ", name = "Field" },
  File = { icon = "", name = "File" },
  Folder = { icon = "", name = "Folder" },
  Function = { icon = "", name = "Func" },
  Interface = { icon = "", name = "Interface" },
  Keyword = { icon = "", name = "Keyword" },
  Method = { icon = "", name = "Method" },
  Module = { icon = "", name = "Module" },
  Operator = { icon = "", name = "Operator" },
  Property = { icon = "ﰠ", name = "Prop" },
  Reference = { icon = "", name = "Ref" },
  Snippet = { icon = "", name = "Snippet" },
  Struct = { icon = "פּ", name = "Struct" },
  Text = { icon = "", name = "Text" },
  TypeParameter = { icon = "", name = "TypeParam" },
  Unit = { icon = "塞", name = "Unit" },
  Value = { icon = "", name = "Value" },
  Variable = { icon = "", name = "Variable" },
}


M.todo_comments = {
  FIX = "律",
  TODO = "璘",
  HACK = " ",
  WARN = "裂",
  PERF = "龍",
  NOTE = " ",
  ERROR = " ",
  REFS = "",
  SHIELD = "",
}

M.symbols_outline = {
  File = "",
  Module = "",
  Namespace = "",
  Package = "",
  Class = "",
  Method = "ƒ",
  Property = "",
  Field = "",
  Constructor = "",
  Enum = "練",
  Interface = "ﰮ",
  Function = "",
  Variable = "",
  Constant = "",
  String = "𝓐",
  Number = "#",
  Boolean = "⊨",
  Array = "",
  Object = "⦿",
  Key = "",
  Null = "NULL",
  EnumMember = "",
  Struct = "פּ",
  Event = "",
  Operator = "",
  TypeParameter = "𝙏",
}

M.icons = {
  error = " ",
  warn = " ",
  info = "",
  hint = " ",
  code_action = "",
  code_lens_action = "",
  test = "",
  docs = "",
  clock = " ",
  calendar = " ",
  buffer = " ",
  settings = " ",
  ls_inactive = "轢",
  ls_active = "歷",
  question = " ",
  screen = "冷",
  dart = " ",
  config = " ",
  git = " ",
  magic = " ",
  exit = " ",
  repo = "",
  term = " ",
}

return M
