local icons = {
  Text = { icon = "", name = "Text" },
  Method = { icon = "", name = "Method" },
  Function = { icon = "", name = "Func" },
  Constructor = { icon = "", name = "Ctor" },
  Field = { icon = "ﰠ", name = "Field" },
  Variable = { icon = "", name = "Variable" },
  Class = { icon = "ﴯ", name = "Class" },
  Interface = { icon = "", name = "Interface" },
  Module = { icon = "", name = "Module" },
  Property = { icon = "ﰠ", name = "Prop" },
  Unit = { icon = "塞", name = "Unit" },
  Value = { icon = "", name = "Value" },
  Enum = { icon = "", name = "Enum" },
  Keyword = { icon = "", name = "Keyword" },
  Snippet = { icon = "", name = "Snippet" },
  Color = { icon = "", name = "Color" },
  File = { icon = "", name = "File" },
  Reference = { icon = "", name = "Ref" },
  Folder = { icon = "", name = "Folder" },
  EnumMember = { icon = "", name = "EnumMember" },
  Constant = { icon = "", name = "Const" },
  Struct = { icon = "פּ", name = "Struct" },
  Event = { icon = "", name = "Event" },
  Operator = { icon = "", name = "Operator" },
  TypeParameter = { icon = "", name = "TypeParam" },
}

return icons
