local configs = require('nvim-treesitter.configs')

configs.setup({
  ensure_installed = {
    'bash',
    'c',
    'cpp',
    'html',
    'javascript',
    'lua',
    'markdown',
    'markdown_inline',
    'python',
    'regex',
    'rust',
    'tsx',
    'typescript',
    'vim',
    'vue',
  },
  sync_install = false,
  highlight = { enable = not vim.g.vscode },
  indent = { enable = true },
  textobjects = {
    select = {
      enable = true,
      -- Automatically jump forward to textobj, similar to targets.vim
      lookahead = true,
      keymaps = {
        ['af'] = '@function.outer',
        ['if'] = '@function.inner',
        ['ac'] = '@class.outer',
        ['ic'] = '@class.inner',
        ['aa'] = '@assignment.outer',
        ['ia'] = '@assignment.inner',
        ['am'] = '@comment.outer',
        ['im'] = '@comment.inner',
        ['ad'] = '@conditional.outer',
        ['id'] = '@conditional.inner',
        ['ao'] = '@loop.outer',
        ['io'] = '@loop.inner',
        ['ap'] = '@parameter.outer',
        ['ip'] = '@parameter.inner',
        ['at'] = '@tag.outer',
        ['it'] = '@tag.inner',
      },
    },
    move = {
      enable = true,
      set_jumps = true,
      goto_next_start = {
        [']f'] = '@function.outer',
        [']c'] = '@class.outer',
        [']a'] = '@assignment.outer',
        [']m'] = '@comment.outer',
        [']d'] = '@conditional.outer',
        [']o'] = '@loop.outer',
        [']p'] = '@parameter.outer',
        [']t'] = '@tag.outer',
      },
      goto_next_end = {},
      goto_previous_start = {
        ['[f'] = '@function.outer',
        ['[c'] = '@class.outer',
        ['[a'] = '@assignment.outer',
        ['[m'] = '@comment.outer',
        ['[d'] = '@conditional.outer',
        ['[o'] = '@loop.outer',
        ['[p'] = '@parameter.outer',
        ['[t'] = '@tag.outer',
      },
      goto_previous_end = {},
    },
  },
})
